# Generated by Django 6.0.4 on 2026-04-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=64, verbose_name='Стол')),
                ('seats_count', models.PositiveIntegerField(default=2, verbose_name='Количество мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_combinable', models.BooleanField(default=False, verbose_name='Можно объединять')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='halls.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['name'],
            },
        ),
    ]
