# Generated by Django 6.0.4 on 2026-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenueBookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('default_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Длительность по умолчанию')),
                ('slot_step_minutes', models.PositiveIntegerField(default=10, verbose_name='Шаг слота')),
                ('cleanup_buffer_minutes', models.PositiveIntegerField(default=20, verbose_name='Буфер на уборку')),
                ('payment_hold_minutes', models.PositiveIntegerField(default=30, verbose_name='Удержание неоплаченной брони')),
                ('requires_manager_confirmation', models.BooleanField(default=True, verbose_name='Требует подтверждения')),
                ('allow_client_approximate_time', models.BooleanField(default=False, verbose_name='Разрешить клиенту примерное время')),
                ('allow_table_combination', models.BooleanField(default=False, verbose_name='Разрешить объединение столов')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма предоплаты')),
                ('deposit_currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Правило бронирования',
                'verbose_name_plural': 'Правила бронирования',
            },
        ),
    ]
