# Generated by Django 6.0.4 on 2026-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rules', '0004_venuebookingrule_cancellation_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuebookingrule',
            name='allow_manager_reschedule',
            field=models.BooleanField(default=True, verbose_name='Разрешить менеджеру переносить бронь'),
        ),
    ]
