# Generated by ChatGPT on 2026-06-15

from django.db import migrations, models


DEFAULT_WORKING_HOURS = {
    str(day): {
        'is_closed': False,
        'opens_at': '00:00',
        'closes_at': '23:59',
    }
    for day in range(7)
}


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rules', '0006_booking_price_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuebookingrule',
            name='working_hours',
            field=models.JSONField(default=DEFAULT_WORKING_HOURS, verbose_name='График работы'),
        ),
    ]
