# Generated by Django 6.0.4 on 2026-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('guests_count', models.PositiveIntegerField(default=1, verbose_name='Количество гостей')),
                ('booking_start', models.DateTimeField(verbose_name='Начало брони')),
                ('booking_end', models.DateTimeField(verbose_name='Конец брони')),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Бронь истекает')),
                ('status', models.CharField(choices=[('pending_confirmation', 'Ожидает подтверждения'), ('waiting_for_payment', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('no_show', 'Неявка')], default='pending_confirmation', max_length=32, verbose_name='Статус')),
                ('customer_comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-booking_start'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('old_status', models.CharField(blank=True, max_length=32, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=32, verbose_name='Новый статус')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'История статуса брони',
                'verbose_name_plural': 'История статусов брони',
            },
        ),
    ]
