# Generated by Django 6.0.4 on 2026-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancellation_and_no_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('hold', 'Зарезервировано'), ('pending_confirmation', 'Ожидает подтверждения'), ('waiting_for_payment', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('no_show', 'Неявка')], default='pending_confirmation', max_length=32, verbose_name='Статус'),
        ),
    ]
