# Generated by Django 6.0.6 on 2026-06-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_type_and_pricing'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tables.table', verbose_name='Основной стол'),
        ),
    ]
