DEMO_PASSWORD = "DemoPass123!"

DEMO_USERS = [
    {
        "key": "owner_main",
        "email": "owner@webtavern.local",
        "phone": "+79990000001",
        "first_name": "Сергей",
        "last_name": "Яковлев",
        "middle_name": "Сергеевич",
        "role": "owner",
        "account_type": "individual",
        "date_of_birth": "2002-06-15",
        "city": "Нижний Новгород",
        "is_staff": False,
    },
    {
        "key": "owner_moscow",
        "email": "owner-moscow@webtavern.local",
        "phone": "+79990000007",
        "first_name": "Виктор",
        "last_name": "Лебедев",
        "middle_name": "Алексеевич",
        "role": "owner",
        "account_type": "legal",
        "date_of_birth": "1990-05-17",
        "city": "Москва",
        "is_staff": False,
    },
    {
        "key": "owner_spb",
        "email": "owner-spb@webtavern.local",
        "phone": "+79990000008",
        "first_name": "Елена",
        "last_name": "Морозова",
        "middle_name": "Павловна",
        "role": "owner",
        "account_type": "legal",
        "date_of_birth": "1991-12-09",
        "city": "Санкт-Петербург",
        "is_staff": False,
    },
    {
        "key": "owner_regions",
        "email": "owner-regions@webtavern.local",
        "phone": "+79990000009",
        "first_name": "Артём",
        "last_name": "Данилов",
        "middle_name": "Игоревич",
        "role": "owner",
        "account_type": "legal",
        "date_of_birth": "1988-03-24",
        "city": "Екатеринбург",
        "is_staff": False,
    },
    {
        "key": "manager_main",
        "email": "manager@webtavern.local",
        "phone": "+79990000002",
        "first_name": "Анна",
        "last_name": "Крылова",
        "middle_name": "Игоревна",
        "role": "manager",
        "account_type": "individual",
        "date_of_birth": "1998-02-20",
        "city": "Нижний Новгород",
        "is_staff": False,
    },
    {
        "key": "manager_alt",
        "email": "manager-alt@webtavern.local",
        "phone": "+79990000010",
        "first_name": "Дмитрий",
        "last_name": "Смирнов",
        "middle_name": "Олегович",
        "role": "manager",
        "account_type": "individual",
        "date_of_birth": "1997-07-11",
        "city": "Москва",
        "is_staff": False,
    },
    {
        "key": "client_main",
        "email": "client@webtavern.local",
        "phone": "+79990000003",
        "first_name": "Илья",
        "last_name": "Волков",
        "middle_name": "Андреевич",
        "role": "client",
        "account_type": "individual",
        "date_of_birth": "2001-10-08",
        "city": "Казань",
        "is_staff": False,
    },
    {
        "key": "client_legal",
        "email": "legal-client@webtavern.local",
        "phone": "+79990000004",
        "first_name": "Мария",
        "last_name": "Соколова",
        "middle_name": "Олеговна",
        "role": "client",
        "account_type": "legal",
        "date_of_birth": "1996-04-12",
        "city": "Москва",
        "is_staff": False,
    },
    {
        "key": "moderator_main",
        "email": "moderator@webtavern.local",
        "phone": "+79990000005",
        "first_name": "Олег",
        "last_name": "Романов",
        "middle_name": "Викторович",
        "role": "moderator",
        "account_type": "individual",
        "date_of_birth": "1995-08-22",
        "city": "Нижний Новгород",
        "is_staff": True,
    },
    {
        "key": "platform_admin",
        "email": "admin@webtavern.local",
        "phone": "+79990000006",
        "first_name": "Платформа",
        "last_name": "Администратор",
        "middle_name": "",
        "role": "platform_admin",
        "account_type": "individual",
        "date_of_birth": "1994-01-01",
        "city": "Нижний Новгород",
        "is_staff": True,
    },
]

DEMO_LEGAL_ENTITIES = [
    {
        "key": "tavern_group",
        "owner": "owner_main",
        "company_name": 'ООО "Tavern Group"',
        "tax_number": "5260123456",
        "registration_number": "1234567890123",
        "legal_address": "г. Нижний Новгород, ул. Рождественская, д. 18",
    },
    {
        "key": "capital_foods",
        "owner": "owner_moscow",
        "company_name": 'ООО "Capital Foods"',
        "tax_number": "7705123456",
        "registration_number": "1234567890124",
        "legal_address": "г. Москва, ул. Мясницкая, д. 19",
    },
    {
        "key": "neva_places",
        "owner": "owner_spb",
        "company_name": 'ООО "Neva Places"',
        "tax_number": "7806123456",
        "registration_number": "1234567890125",
        "legal_address": "г. Санкт-Петербург, наб. реки Фонтанки, д. 38",
    },
    {
        "key": "regional_table",
        "owner": "owner_regions",
        "company_name": 'ООО "Regional Table"',
        "tax_number": "6658123456",
        "registration_number": "1234567890126",
        "legal_address": "г. Екатеринбург, пр. Ленина, д. 44",
    },
]


PRESET_THEME_BASE = {
    "northern_blue": {
        "theme_mode": "dark",
        "accent_color": "#2563eb",
        "background_variant": "graphite-grid",
        "text_color": "#e5eefc",
        "card_background_color": "#0f172a",
        "card_text_color": "#e5eefc",
        "badge_background_color": "#dbeafe",
        "badge_text_color": "#1e3a8a",
        "cta_background_color": "#2563eb",
        "cta_text_color": "#ffffff",
    },
    "night_neon": {
        "theme_mode": "dark",
        "accent_color": "#7c3aed",
        "background_variant": "dark-soft",
        "text_color": "#f5f3ff",
        "card_background_color": "#111827",
        "card_text_color": "#f5f3ff",
        "badge_background_color": "#312e81",
        "badge_text_color": "#e0e7ff",
        "cta_background_color": "#7c3aed",
        "cta_text_color": "#ffffff",
    },
    "sea_breeze": {
        "theme_mode": "light",
        "accent_color": "#0284c7",
        "background_variant": "cool-gradient",
        "text_color": "#0f172a",
        "card_background_color": "#ecfeff",
        "card_text_color": "#164e63",
        "badge_background_color": "#cffafe",
        "badge_text_color": "#155e75",
        "cta_background_color": "#0369a1",
        "cta_text_color": "#ffffff",
    },
    "amber_craft": {
        "theme_mode": "light",
        "accent_color": "#d97706",
        "background_variant": "warm-gradient",
        "text_color": "#3f2b1c",
        "card_background_color": "#fffbeb",
        "card_text_color": "#78350f",
        "badge_background_color": "#fef3c7",
        "badge_text_color": "#92400e",
        "cta_background_color": "#b45309",
        "cta_text_color": "#ffffff",
    },
    "coffee_sand": {
        "theme_mode": "light",
        "accent_color": "#92400e",
        "background_variant": "warm-gradient",
        "text_color": "#3f2b1c",
        "card_background_color": "#fef3c7",
        "card_text_color": "#78350f",
        "badge_background_color": "#fde68a",
        "badge_text_color": "#92400e",
        "cta_background_color": "#92400e",
        "cta_text_color": "#ffffff",
    },
    "mint_minimal": {
        "theme_mode": "light",
        "accent_color": "#0f766e",
        "background_variant": "neutral-surface",
        "text_color": "#0f172a",
        "card_background_color": "#f0fdfa",
        "card_text_color": "#134e4a",
        "badge_background_color": "#ccfbf1",
        "badge_text_color": "#115e59",
        "cta_background_color": "#0f766e",
        "cta_text_color": "#ffffff",
    },
    "graphite_gold": {
        "theme_mode": "dark",
        "accent_color": "#f59e0b",
        "background_variant": "graphite-grid",
        "text_color": "#f8fafc",
        "card_background_color": "#111827",
        "card_text_color": "#f8fafc",
        "badge_background_color": "#fef3c7",
        "badge_text_color": "#92400e",
        "cta_background_color": "#d97706",
        "cta_text_color": "#111827",
    },
    "cherry_noir": {
        "theme_mode": "dark",
        "accent_color": "#e11d48",
        "background_variant": "dark-soft",
        "text_color": "#fff1f2",
        "card_background_color": "#2b0b12",
        "card_text_color": "#ffe4e6",
        "badge_background_color": "#ffe4e6",
        "badge_text_color": "#9f1239",
        "cta_background_color": "#be123c",
        "cta_text_color": "#ffffff",
    },
    "lavender_soft": {
        "theme_mode": "light",
        "accent_color": "#8b5cf6",
        "background_variant": "soft-paper",
        "text_color": "#1f2937",
        "card_background_color": "#faf5ff",
        "card_text_color": "#4c1d95",
        "badge_background_color": "#ede9fe",
        "badge_text_color": "#5b21b6",
        "cta_background_color": "#7c3aed",
        "cta_text_color": "#ffffff",
    },
    "forest_ember": {
        "theme_mode": "dark",
        "accent_color": "#f97316",
        "background_variant": "pattern-soft",
        "text_color": "#f7fee7",
        "card_background_color": "#1f2a1d",
        "card_text_color": "#f7fee7",
        "badge_background_color": "#dcfce7",
        "badge_text_color": "#14532d",
        "cta_background_color": "#ea580c",
        "cta_text_color": "#ffffff",
    },
    "steel_business": {
        "theme_mode": "light",
        "accent_color": "#475569",
        "background_variant": "neutral-surface",
        "text_color": "#111827",
        "card_background_color": "#f8fafc",
        "card_text_color": "#1e293b",
        "badge_background_color": "#e2e8f0",
        "badge_text_color": "#334155",
        "cta_background_color": "#334155",
        "cta_text_color": "#ffffff",
    },
}


def _branding(preset, custom=None):
    data = PRESET_THEME_BASE.get(preset, PRESET_THEME_BASE["northern_blue"]).copy()
    data["theme_preset"] = preset
    data["use_custom_palette"] = False
    data["contrast_warning"] = False
    if custom:
        data.update(custom)
        data["use_custom_palette"] = True
    return data


def _decor_items():
    return [
        {"item_type": "entrance", "label": "Вход", "x": 40, "y": 690, "width": 150, "height": 42},
        {"item_type": "bar", "label": "Бар", "x": 880, "y": 60, "width": 220, "height": 80},
        {"item_type": "plant", "label": "Зелень", "x": 1040, "y": 630, "width": 90, "height": 90},
        {"item_type": "window", "label": "Окна", "x": 260, "y": 20, "width": 420, "height": 36},
    ]


DEMO_VENUES = [
    {
        "key": "north_harbor",
        "owner": "owner_main",
        "legal_entity": "tavern_group",
        "name": "North Harbor",
        "slug": "north-harbor",
        "country": "Россия",
        "city": "Нижний Новгород",
        "district": "Нижегородский",
        "address": "ул. Большая Покровская, 22",
        "latitude": "56.324062",
        "longitude": "44.005391",
        "cuisine": "Европейская",
        "price_category": "middle",
        "venue_theme": "business",
        "short_description": "Современное городское бистро с мягким светом и живой посадкой.",
        "description": "Заведение тестового контура с акцентом на вечерние брони, настольные встречи и деловые ужины.",
        "status": "active",
        "average_rating": "4.70",
        "is_published": True,
        "branding": _branding("night_neon"),
        "booking_rule": {
            "default_duration_minutes": 60,
            "slot_step_minutes": 10,
            "cleanup_buffer_minutes": 20,
            "payment_hold_minutes": 30,
            "requires_manager_confirmation": True,
            "allow_client_approximate_time": True,
            "allow_table_combination": True,
            "allow_shared_seating": False,
            "deposit_amount": "600.00",
            "deposit_currency": "RUB",
        },
        "manager_keys": ["manager_main"],
        "halls": [
            {
                "key": "north_main_hall",
                "name": "Основной зал",
                "description": "Общий зал с панорамными окнами.",
                "capacity": 32,
                "sort_order": 1,
                "layout": {"canvas_width": 1200, "canvas_height": 800},
                "decor_items": _decor_items(),
                "tables": [
                    {"key": "north_t1", "name": "T1", "seats_count": 2, "is_combinable": True, "x": 80, "y": 90},
                    {"key": "north_t2", "name": "T2", "seats_count": 2, "is_combinable": True, "x": 240, "y": 90},
                    {"key": "north_t3", "name": "T3", "seats_count": 4, "is_combinable": False, "x": 440, "y": 120},
                    {"key": "north_t4", "name": "T4", "seats_count": 6, "is_combinable": False, "x": 700, "y": 170},
                    {"key": "north_t5", "name": "T5", "seats_count": 4, "is_combinable": True, "x": 480, "y": 350},
                ],
            },
            {
                "key": "north_lounge",
                "name": "Lounge-зона",
                "description": "Полузакрытая зона для небольших компаний.",
                "capacity": 18,
                "sort_order": 2,
                "layout": {"canvas_width": 1000, "canvas_height": 700},
                "decor_items": [
                    {"item_type": "sofa", "label": "Диван", "x": 60, "y": 520, "width": 260, "height": 70},
                    {"item_type": "plant", "label": "Растения", "x": 830, "y": 80, "width": 80, "height": 80},
                ],
                "tables": [
                    {"key": "north_l1", "name": "L1", "seats_count": 4, "is_combinable": False, "x": 120, "y": 140},
                    {"key": "north_l2", "name": "L2", "seats_count": 4, "is_combinable": False, "x": 320, "y": 140},
                    {"key": "north_l3", "name": "L3", "seats_count": 6, "is_combinable": True, "x": 580, "y": 210},
                ],
            },
        ],
    },
    {
        "key": "pixel_sakura",
        "owner": "owner_main",
        "legal_entity": "tavern_group",
        "name": "Pixel Sakura",
        "slug": "pixel-sakura",
        "country": "Россия",
        "city": "Казань",
        "district": "Вахитовский",
        "address": "ул. Баумана, 7",
        "latitude": "55.790278",
        "longitude": "49.114444",
        "cuisine": "Паназиатская",
        "price_category": "high",
        "venue_theme": "geek",
        "short_description": "Атмосферное заведение с тематическими вечерами и тихими зонами.",
        "description": "Второе тестовое заведение для проверки мультизаведений, листа ожидания и раздельной аналитики.",
        "status": "pending_moderation",
        "average_rating": "4.30",
        "is_published": False,
        "branding": _branding("lavender_soft"),
        "booking_rule": {
            "default_duration_minutes": 90,
            "slot_step_minutes": 10,
            "cleanup_buffer_minutes": 20,
            "payment_hold_minutes": 30,
            "requires_manager_confirmation": True,
            "allow_client_approximate_time": False,
            "allow_table_combination": False,
            "allow_shared_seating": False,
            "deposit_amount": "900.00",
            "deposit_currency": "RUB",
        },
        "manager_keys": ["manager_main"],
        "halls": [
            {
                "key": "pixel_event",
                "name": "Event hall",
                "description": "Зал для мероприятий и стримов.",
                "capacity": 26,
                "sort_order": 1,
                "layout": {"canvas_width": 1200, "canvas_height": 900},
                "decor_items": [
                    {"item_type": "label", "label": "Экран", "x": 780, "y": 80, "width": 260, "height": 72},
                    {"item_type": "plant", "label": "Сакура", "x": 90, "y": 620, "width": 90, "height": 90},
                ],
                "tables": [
                    {"key": "pixel_e1", "name": "E1", "seats_count": 4, "is_combinable": False, "x": 110, "y": 120},
                    {"key": "pixel_e2", "name": "E2", "seats_count": 4, "is_combinable": False, "x": 320, "y": 120},
                    {"key": "pixel_e3", "name": "E3", "seats_count": 8, "is_combinable": True, "x": 620, "y": 180},
                ],
            }
        ],
    },
]


def _build_extra_demo_venue(
    *,
    key,
    owner,
    legal_entity,
    manager_keys,
    name,
    slug,
    city,
    district,
    address,
    lat,
    lng,
    cuisine,
    price_category,
    venue_theme,
    preset,
    short_description,
    description,
    rating,
    deposit_amount,
    requires_manager_confirmation=False,
    allow_shared_seating=True,
):
    table_specs = [
        ("T1", 2, 90, 100),
        ("T2", 4, 280, 100),
        ("T3", 4, 480, 170),
        ("T4", 6, 730, 230),
        ("T5", 4, 280, 350),
        ("T6", 2, 700, 470),
    ]
    tables = [
        {
            "key": f"{key}_t{index}",
            "name": label,
            "seats_count": seats,
            "is_combinable": seats <= 4,
            "x": x,
            "y": y,
        }
        for index, (label, seats, x, y) in enumerate(table_specs, start=1)
    ]
    return {
        "key": key,
        "owner": owner,
        "legal_entity": legal_entity,
        "name": name,
        "slug": slug,
        "country": "Россия",
        "city": city,
        "district": district,
        "address": address,
        "latitude": lat,
        "longitude": lng,
        "cuisine": cuisine,
        "price_category": price_category,
        "venue_theme": venue_theme,
        "short_description": short_description,
        "description": description,
        "status": "active",
        "average_rating": rating,
        "is_published": True,
        "branding": _branding(preset),
        "booking_rule": {
            "default_duration_minutes": 60,
            "slot_step_minutes": 10,
            "cleanup_buffer_minutes": 20,
            "payment_hold_minutes": 30,
            "requires_manager_confirmation": requires_manager_confirmation,
            "allow_client_approximate_time": True,
            "allow_table_combination": True,
            "allow_shared_seating": allow_shared_seating,
            "deposit_amount": deposit_amount,
            "deposit_currency": "RUB",
        },
        "manager_keys": manager_keys,
        "halls": [
            {
                "key": f"{key}_hall",
                "name": "Основной зал",
                "description": "Демо-зал для каталога, выбора стола и проверки геофильтров.",
                "capacity": sum(table[1] for table in table_specs),
                "sort_order": 1,
                "layout": {"canvas_width": 1200, "canvas_height": 800},
                "decor_items": _decor_items(),
                "tables": tables,
            }
        ],
    }


DEMO_VENUES.extend([
    _build_extra_demo_venue(
        key="aurora_moscow",
        owner="owner_moscow",
        legal_entity="capital_foods",
        manager_keys=["manager_alt"],
        name="Aurora Room",
        slug="aurora-room",
        city="Москва",
        district="Басманный",
        address="ул. Мясницкая, 19",
        lat="55.761791",
        lng="37.637907",
        cuisine="Авторская",
        price_category="premium",
        venue_theme="business",
        preset="steel_business",
        short_description="Тихий городской ресторан для встреч и вечерних броней.",
        description="Демонстрационное заведение в центре Москвы с одной активной схемой зала и онлайн-бронированием.",
        rating="4.80",
        deposit_amount="900.00",
        requires_manager_confirmation=True,
        allow_shared_seating=False,
    ),
    _build_extra_demo_venue(
        key="neva_loft",
        owner="owner_spb",
        legal_entity="neva_places",
        manager_keys=["manager_alt"],
        name="Neva Loft",
        slug="neva-loft",
        city="Санкт-Петербург",
        district="Центральный",
        address="наб. реки Фонтанки, 38",
        lat="59.929101",
        lng="30.342715",
        cuisine="Европейская",
        price_category="high",
        venue_theme="lounge",
        preset="sea_breeze",
        short_description="Светлый loft-формат для компаний и спокойных поздних ужинов.",
        description="Демо-площадка для каталога с фокусом на простое бронирование без лишних шагов.",
        rating="4.60",
        deposit_amount="500.00",
        requires_manager_confirmation=False,
    ),
    _build_extra_demo_venue(
        key="ural_yard",
        owner="owner_regions",
        legal_entity="regional_table",
        manager_keys=["manager_alt"],
        name="Ural Yard",
        slug="ural-yard",
        city="Екатеринбург",
        district="Кировский",
        address="пр. Ленина, 44",
        lat="56.838607",
        lng="60.614603",
        cuisine="Гастробар",
        price_category="middle",
        venue_theme="geek",
        preset="forest_ember",
        short_description="Пространство для дружеских встреч и настольных вечеров.",
        description="Екатеринбургский демо-ресторан с наглядной схемой зала и доступным менеджеру бронированием.",
        rating="4.50",
        deposit_amount="400.00",
        requires_manager_confirmation=True,
    ),
    _build_extra_demo_venue(
        key="siberia_station",
        owner="owner_regions",
        legal_entity="regional_table",
        manager_keys=["manager_alt"],
        name="Siberia Station",
        slug="siberia-station",
        city="Новосибирск",
        district="Центральный",
        address="Красный проспект, 25",
        lat="55.030204",
        lng="82.920430",
        cuisine="Сибирская",
        price_category="middle",
        venue_theme="family",
        preset="northern_blue",
        short_description="Уютный ресторан возле центра с быстрым подтверждением броней.",
        description="Демо-объект для проверки поиска по крупным городам России и фильтров по типу подтверждения.",
        rating="4.40",
        deposit_amount="350.00",
        requires_manager_confirmation=False,
    ),
    _build_extra_demo_venue(
        key="black_sea_table",
        owner="owner_regions",
        legal_entity="regional_table",
        manager_keys=["manager_main"],
        name="Black Sea Table",
        slug="black-sea-table",
        city="Сочи",
        district="Центральный",
        address="ул. Навагинская, 11",
        lat="43.585472",
        lng="39.723098",
        cuisine="Черноморская",
        price_category="high",
        venue_theme="panoramic",
        preset="sea_breeze",
        short_description="Курортный формат для спокойных семейных посещений.",
        description="Демо-заведение в Сочи для выбора стола на схеме и просмотра текущей занятости.",
        rating="4.90",
        deposit_amount="700.00",
        requires_manager_confirmation=True,
    ),
    _build_extra_demo_venue(
        key="pacific_note",
        owner="owner_regions",
        legal_entity="regional_table",
        manager_keys=["manager_alt"],
        name="Pacific Note",
        slug="pacific-note",
        city="Владивосток",
        district="Ленинский",
        address="ул. Светланская, 15",
        lat="43.115542",
        lng="131.885494",
        cuisine="Паназиатская",
        price_category="middle",
        venue_theme="panoramic",
        preset="mint_minimal",
        short_description="Небольшой ресторан с видом на вечерний город и гибкой посадкой.",
        description="Владивостокская точка в демонстрационном каталоге с активной схемой зала.",
        rating="4.55",
        deposit_amount="450.00",
        requires_manager_confirmation=False,
    ),
    _build_extra_demo_venue(
        key="amber_port",
        owner="owner_spb",
        legal_entity="neva_places",
        manager_keys=["manager_alt"],
        name="Amber Port",
        slug="amber-port",
        city="Калининград",
        district="Ленинградский",
        address="Ленинский проспект, 9",
        lat="54.710426",
        lng="20.510583",
        cuisine="Балтийская",
        price_category="middle",
        venue_theme="romantic",
        preset="amber_craft",
        short_description="Небольшой ресторан с мягким интерьером и вечерним потоком гостей.",
        description="Калининградская демо-локация для фильтрации по городам и бронирований через схему зала.",
        rating="4.35",
        deposit_amount="300.00",
        requires_manager_confirmation=True,
    ),
    _build_extra_demo_venue(
        key="yenisei_hall",
        owner="owner_regions",
        legal_entity="regional_table",
        manager_keys=["manager_alt"],
        name="Yenisei Hall",
        slug="yenisei-hall",
        city="Красноярск",
        district="Центральный",
        address="пр. Мира, 73",
        lat="56.009657",
        lng="92.852545",
        cuisine="Сибирская",
        price_category="middle",
        venue_theme="business",
        preset="graphite_gold",
        short_description="Заведение для деловых обедов и небольших компаний.",
        description="Демо-ресторан в Красноярске с автоподтверждением броней и простой схемой зала.",
        rating="4.45",
        deposit_amount="350.00",
        requires_manager_confirmation=False,
    ),
    _build_extra_demo_venue(
        key="volga_room",
        owner="owner_main",
        legal_entity="tavern_group",
        manager_keys=["manager_main"],
        name="Volga Room",
        slug="volga-room",
        city="Самара",
        district="Самарский",
        address="ул. Куйбышева, 96",
        lat="53.195538",
        lng="50.101783",
        cuisine="Европейская",
        price_category="middle",
        venue_theme="lounge",
        preset="coffee_sand",
        short_description="Мягкий камерный формат для встреч и семейных ужинов.",
        description="Ещё одна активная точка каталога с возможностью быстро выбрать стол на схеме.",
        rating="4.52",
        deposit_amount="380.00",
        requires_manager_confirmation=True,
    ),
    _build_extra_demo_venue(
        key="don_lane",
        owner="owner_moscow",
        legal_entity="capital_foods",
        manager_keys=["manager_alt"],
        name="Don Lane",
        slug="don-lane",
        city="Ростов-на-Дону",
        district="Кировский",
        address="ул. Пушкинская, 133",
        lat="47.222078",
        lng="39.728355",
        cuisine="Южная",
        price_category="middle",
        venue_theme="live_music",
        preset="cherry_noir",
        short_description="Южное городское заведение для свободных и быстрых броней.",
        description="Ростовская демо-локация для клиентского поиска, фильтрации и бронирования через столы.",
        rating="4.58",
        deposit_amount="420.00",
        requires_manager_confirmation=False,
    ),
    _build_extra_demo_venue(
        key="quiet_leaf",
        owner="owner_spb",
        legal_entity="neva_places",
        manager_keys=["manager_alt"],
        name="Quiet Leaf",
        slug="quiet-leaf",
        city="Нижний Новгород",
        district="Советский",
        address="ул. Белинского, 61",
        lat="56.313943",
        lng="44.029297",
        cuisine="Вегетарианская",
        price_category="middle",
        venue_theme="family",
        preset="mint_minimal",
        short_description="Зелёное спокойное место для завтраков, семейных встреч и работы.",
        description="Второе опубликованное заведение в Нижнем Новгороде для проверки районов внутри одного города.",
        rating="4.66",
        deposit_amount="250.00",
        requires_manager_confirmation=False,
    ),
    _build_extra_demo_venue(
        key="indigo_table",
        owner="owner_moscow",
        legal_entity="capital_foods",
        manager_keys=["manager_alt"],
        name="Indigo Table",
        slug="indigo-table",
        city="Москва",
        district="Пресненский",
        address="ул. Рочдельская, 15",
        lat="55.756222",
        lng="37.562617",
        cuisine="Авторская",
        price_category="premium",
        venue_theme="art",
        preset="lavender_soft",
        short_description="Арт-ресторан с насыщенной вечерней атмосферой и камерной посадкой.",
        description="Второе московское заведение для проверки фильтра город → район и разных владельцев.",
        rating="4.77",
        deposit_amount="1000.00",
        requires_manager_confirmation=True,
        allow_shared_seating=False,
    ),
])

# Реальные заведения для расширенного демонстрационного каталога.
# Важно: публичные точные планы помещений большинства заведений недоступны,
# поэтому ниже используются демонстрационные схемы посадки для проверки бронирования.


def _real_demo_tables(prefix, variant="classic"):
    variants = {
        "classic": [
            ("T1", 2, 90, 110, 110, 110), ("T2", 2, 250, 110, 110, 110),
            ("T3", 4, 430, 150, 130, 120), ("T4", 4, 650, 150, 130, 120),
            ("T5", 6, 850, 260, 160, 130), ("T6", 4, 440, 380, 130, 120),
        ],
        "long": [
            ("W1", 2, 90, 95, 105, 105), ("W2", 2, 90, 250, 105, 105),
            ("C1", 4, 330, 120, 130, 120), ("C2", 4, 530, 120, 130, 120),
            ("C3", 6, 760, 190, 165, 130), ("B1", 2, 940, 420, 105, 105),
        ],
        "panorama": [
            ("P1", 2, 130, 90, 110, 110), ("P2", 2, 300, 90, 110, 110),
            ("P3", 4, 500, 105, 130, 120), ("P4", 4, 710, 120, 130, 120),
            ("S1", 6, 250, 340, 165, 130), ("S2", 6, 570, 360, 165, 130),
        ],
        "compact": [
            ("A1", 2, 90, 120, 105, 105), ("A2", 2, 230, 120, 105, 105),
            ("A3", 4, 390, 130, 125, 115), ("A4", 4, 560, 130, 125, 115),
            ("A5", 4, 390, 330, 125, 115), ("A6", 2, 700, 360, 105, 105),
        ],
    }
    return [
        {
            "key": f"{prefix}_{index}",
            "name": label,
            "seats_count": seats,
            "is_combinable": seats <= 4,
            "x": x,
            "y": y,
            "width": width,
            "height": height,
        }
        for index, (label, seats, x, y, width, height) in enumerate(variants.get(variant, variants["classic"]), start=1)
    ]


def _real_demo_decor(variant="classic"):
    base = [
        {"item_type": "entrance", "label": "Вход", "x": 36, "y": 688, "width": 150, "height": 42},
        {"item_type": "bar", "label": "Бар", "x": 890, "y": 70, "width": 220, "height": 78},
        {"item_type": "plant", "label": "Зелень", "x": 1030, "y": 610, "width": 80, "height": 80},
    ]
    if variant == "panorama":
        base.append({"item_type": "window", "label": "Панорамные окна", "x": 180, "y": 20, "width": 660, "height": 34})
    elif variant == "long":
        base.append({"item_type": "sofa", "label": "Диванная линия", "x": 60, "y": 520, "width": 390, "height": 70})
    elif variant == "compact":
        base.append({"item_type": "label", "label": "Касса / хостес", "x": 760, "y": 70, "width": 190, "height": 60})
    else:
        base.append({"item_type": "window", "label": "Окна", "x": 260, "y": 24, "width": 430, "height": 34})
    return base


def _build_real_demo_venue(
    *,
    key,
    owner,
    legal_entity,
    manager_keys,
    name,
    slug,
    city,
    district,
    address,
    lat,
    lng,
    cuisine,
    price_category,
    venue_theme,
    preset,
    short_description,
    description,
    rating,
    deposit_amount,
    layout_variant="classic",
    requires_manager_confirmation=True,
    allow_shared_seating=False,
):
    tables = _real_demo_tables(key, layout_variant)
    return {
        "key": key,
        "owner": owner,
        "legal_entity": legal_entity,
        "name": name,
        "slug": slug,
        "country": "Россия",
        "city": city,
        "district": district,
        "address": address,
        "latitude": lat,
        "longitude": lng,
        "cuisine": cuisine,
        "price_category": price_category,
        "venue_theme": venue_theme,
        "short_description": short_description,
        "description": description,
        "status": "active",
        "average_rating": rating,
        "is_published": True,
        "branding": _branding(preset),
        "booking_rule": {
            "default_duration_minutes": 90,
            "slot_step_minutes": 10,
            "cleanup_buffer_minutes": 20,
            "payment_hold_minutes": 30,
            "requires_manager_confirmation": requires_manager_confirmation,
            "allow_client_approximate_time": True,
            "allow_table_combination": True,
            "allow_shared_seating": allow_shared_seating,
            "deposit_amount": deposit_amount,
            "deposit_currency": "RUB",
        },
        "manager_keys": manager_keys,
        "halls": [
            {
                "key": f"{key}_main",
                "name": "Основной зал",
                "description": "Схема посадки подготовлена для демонстрации бронирования столов на карте зала.",
                "capacity": sum(item["seats_count"] for item in tables),
                "sort_order": 1,
                "layout": {"canvas_width": 1200, "canvas_height": 800},
                "decor_items": _real_demo_decor(layout_variant),
                "tables": tables,
            }
        ],
    }


DEMO_VENUES.extend([
    # Нижний Новгород
    _build_real_demo_venue(
        key="pyatkin_nn",
        owner="owner_main",
        legal_entity="tavern_group",
        manager_keys=["manager_main"],
        name="Пяткин",
        slug="pyatkin-nn",
        city="Нижний Новгород",
        district="Нижегородский",
        address="ул. Рождественская, 25",
        lat="56.328700",
        lng="43.988900",
        cuisine="Русская",
        price_category="high",
        venue_theme="family",
        preset="amber_craft",
        short_description="Исторический ресторан русской кухни на Рождественской улице.",
        description="Реальное заведение добавлено в демонстрационный каталог WebTavern. Схема зала является адаптированной схемой посадки для бронирования.",
        rating="4.70",
        deposit_amount="700.00",
        layout_variant="classic",
    ),
    _build_real_demo_venue(
        key="mitrich_nn",
        owner="owner_main",
        legal_entity="tavern_group",
        manager_keys=["manager_main"],
        name="Митрич Steakhouse",
        slug="mitrich-steakhouse-nn",
        city="Нижний Новгород",
        district="Нижегородский",
        address="ул. Ковалихинская, 8",
        lat="56.323400",
        lng="44.020800",
        cuisine="Стейкхаус",
        price_category="high",
        venue_theme="business",
        preset="graphite_gold",
        short_description="Городской стейкхаус для ужинов, встреч и бронирований на вечер.",
        description="Реальное заведение добавлено для проверки городского каталога и схем посадки. План в системе — демонстрационный контур столов.",
        rating="4.60",
        deposit_amount="800.00",
        layout_variant="long",
    ),

    # Дзержинск
    _build_real_demo_venue(
        key="dodo_dzerzhinsk_tsiolkovskogo",
        owner="owner_main",
        legal_entity="tavern_group",
        manager_keys=["manager_main"],
        name="Додо Пицца на Циолковского",
        slug="dodo-dzerzhinsk-tsiolkovskogo",
        city="Дзержинск",
        district="Центральный",
        address="просп. Циолковского, 76",
        lat="56.238900",
        lng="43.459100",
        cuisine="Пицца",
        price_category="middle",
        venue_theme="fast_casual",
        preset="sea_breeze",
        short_description="Сетевое кафе-пиццерия для быстрых встреч и семейных посещений.",
        description="Реальная городская точка добавлена для проверки Дзержинска в географии WebTavern. План — демонстрационная схема посадки.",
        rating="4.40",
        deposit_amount="300.00",
        layout_variant="compact",
        requires_manager_confirmation=False,
        allow_shared_seating=True,
    ),
    _build_real_demo_venue(
        key="dzerzhinsk_city_cafe",
        owner="owner_main",
        legal_entity="tavern_group",
        manager_keys=["manager_main"],
        name="City Cafe Дзержинск",
        slug="city-cafe-dzerzhinsk",
        city="Дзержинск",
        district="Центральный",
        address="просп. Ленина, 66",
        lat="56.237900",
        lng="43.463800",
        cuisine="Европейская",
        price_category="middle",
        venue_theme="family",
        preset="mint_minimal",
        short_description="Городское кафе для обедов, встреч и небольших компаний.",
        description="Заведение добавлено в демо-каталог для проверки города Дзержинск и выбора столов по схеме.",
        rating="4.35",
        deposit_amount="250.00",
        layout_variant="classic",
        requires_manager_confirmation=False,
    ),

    # Москва
    _build_real_demo_venue(
        key="white_rabbit_moscow",
        owner="owner_moscow",
        legal_entity="capital_foods",
        manager_keys=["manager_alt"],
        name="White Rabbit",
        slug="white-rabbit-moscow",
        city="Москва",
        district="Арбат",
        address="Смоленская площадь, 3",
        lat="55.747500",
        lng="37.582000",
        cuisine="Современная русская",
        price_category="premium",
        venue_theme="panoramic",
        preset="lavender_soft",
        short_description="Панорамный ресторан современной русской кухни в центре Москвы.",
        description="Реальное заведение добавлено для расширения московского каталога. Схема в WebTavern — демонстрационная посадка для проверки бронирования.",
        rating="4.80",
        deposit_amount="1500.00",
        layout_variant="panorama",
        requires_manager_confirmation=True,
    ),
    _build_real_demo_venue(
        key="uzbekistan_moscow",
        owner="owner_moscow",
        legal_entity="capital_foods",
        manager_keys=["manager_alt"],
        name="Узбекистан",
        slug="uzbekistan-moscow",
        city="Москва",
        district="Тверской",
        address="ул. Неглинная, 29, стр. 5",
        lat="55.766000",
        lng="37.620500",
        cuisine="Среднеазиатская",
        price_category="high",
        venue_theme="ethnic",
        preset="coffee_sand",
        short_description="Исторический ресторан среднеазиатской кухни в центре Москвы.",
        description="Реальное заведение добавлено в демонстрационный контур. План зала в системе является адаптированной схемой посадки.",
        rating="4.65",
        deposit_amount="900.00",
        layout_variant="classic",
    ),

    # Екатеринбург
    _build_real_demo_venue(
        key="everjazz_ekb",
        owner="owner_regions",
        legal_entity="regional_table",
        manager_keys=["manager_alt"],
        name="EverJazz",
        slug="everjazz-ekaterinburg",
        city="Екатеринбург",
        district="Кировский",
        address="ул. Тургенева, 22",
        lat="56.843300",
        lng="60.612800",
        cuisine="Клуб / бар",
        price_category="middle",
        venue_theme="live_music",
        preset="cherry_noir",
        short_description="Джаз-клуб с вечерними событиями и камерной посадкой.",
        description="Реальное заведение добавлено для проверки сценариев бронирования на концертные и вечерние слоты.",
        rating="4.70",
        deposit_amount="600.00",
        layout_variant="long",
    ),
    _build_real_demo_venue(
        key="gastroli_ekb",
        owner="owner_regions",
        legal_entity="regional_table",
        manager_keys=["manager_alt"],
        name="Гастроли",
        slug="gastroli-ekaterinburg",
        city="Екатеринбург",
        district="Центральный",
        address="ул. 8 Марта, 4",
        lat="56.838500",
        lng="60.603500",
        cuisine="Авторская",
        price_category="high",
        venue_theme="art",
        preset="forest_ember",
        short_description="Гастрономический ресторан для вечерних встреч и дегустаций.",
        description="Реальное заведение добавлено в каталог WebTavern. Внутренняя схема — демонстрационная карта посадки.",
        rating="4.62",
        deposit_amount="700.00",
        layout_variant="panorama",
    ),

    # Санкт-Петербург
    _build_real_demo_venue(
        key="literary_cafe_spb",
        owner="owner_spb",
        legal_entity="neva_places",
        manager_keys=["manager_alt"],
        name="Литературное кафе",
        slug="literary-cafe-spb",
        city="Санкт-Петербург",
        district="Центральный",
        address="Невский проспект, 18",
        lat="59.935500",
        lng="30.323600",
        cuisine="Русская / европейская",
        price_category="high",
        venue_theme="romantic",
        preset="amber_craft",
        short_description="Историческое кафе-ресторан на Невском проспекте.",
        description="Реальное заведение добавлено для проверки петербургского каталога. План в системе — адаптированная схема посадки.",
        rating="4.55",
        deposit_amount="650.00",
        layout_variant="classic",
    ),
    _build_real_demo_venue(
        key="palkin_spb",
        owner="owner_spb",
        legal_entity="neva_places",
        manager_keys=["manager_alt"],
        name="Палкинъ",
        slug="palkin-spb",
        city="Санкт-Петербург",
        district="Центральный",
        address="Невский проспект, 47",
        lat="59.932300",
        lng="30.348000",
        cuisine="Русская / европейская",
        price_category="premium",
        venue_theme="business",
        preset="steel_business",
        short_description="Классический ресторан для деловых ужинов и торжественных встреч.",
        description="Реальное заведение добавлено в демо-версию WebTavern. Схема отображает демонстрационную посадку столов.",
        rating="4.68",
        deposit_amount="1100.00",
        layout_variant="long",
    ),

    # Владивосток
    _build_real_demo_venue(
        key="benuar_vladivostok",
        owner="owner_regions",
        legal_entity="regional_table",
        manager_keys=["manager_alt"],
        name="BENUAR by The Toy Moscow",
        slug="benuar-vladivostok",
        city="Владивосток",
        district="Фрунзенский",
        address="Корабельная набережная, 10",
        lat="43.116100",
        lng="131.889200",
        cuisine="Авторская",
        price_category="premium",
        venue_theme="art",
        preset="graphite_gold",
        short_description="Шоу-ресторан в формате dinner & show у морского порта.",
        description="Реальное заведение добавлено для проверки дальневосточного каталога. Схема в системе — демонстрационная посадка.",
        rating="4.75",
        deposit_amount="1300.00",
        layout_variant="panorama",
    ),
    _build_real_demo_venue(
        key="zuma_vladivostok",
        owner="owner_regions",
        legal_entity="regional_table",
        manager_keys=["manager_alt"],
        name="Zuma",
        slug="zuma-vladivostok",
        city="Владивосток",
        district="Фрунзенский",
        address="ул. Фонтанная, 2",
        lat="43.119600",
        lng="131.884500",
        cuisine="Паназиатская",
        price_category="high",
        venue_theme="ethnic",
        preset="sea_breeze",
        short_description="Паназиатский ресторан для вечерних посещений и компаний.",
        description="Реальное заведение добавлено в каталог. Схема зала в WebTavern — адаптированный план посадки.",
        rating="4.70",
        deposit_amount="800.00",
        layout_variant="classic",
    ),

    # Севастополь
    _build_real_demo_venue(
        key="barkas_sevastopol",
        owner="owner_spb",
        legal_entity="neva_places",
        manager_keys=["manager_alt"],
        name="Баркас",
        slug="barkas-sevastopol",
        city="Севастополь",
        district="Ленинский",
        address="Артиллерийская бухта, 1А",
        lat="44.613900",
        lng="33.523400",
        cuisine="Рыбная / черноморская",
        price_category="high",
        venue_theme="panoramic",
        preset="sea_breeze",
        short_description="Рыбный ресторан у городской бухты.",
        description="Реальное заведение добавлено для проверки города Севастополь и морской тематики в каталоге.",
        rating="4.63",
        deposit_amount="700.00",
        layout_variant="panorama",
    ),
    _build_real_demo_venue(
        key="ostrov_sevastopol",
        owner="owner_spb",
        legal_entity="neva_places",
        manager_keys=["manager_alt"],
        name="Остров",
        slug="ostrov-sevastopol",
        city="Севастополь",
        district="Гагаринский",
        address="просп. Октябрьской Революции, 43",
        lat="44.586500",
        lng="33.457900",
        cuisine="Европейская",
        price_category="middle",
        venue_theme="family",
        preset="mint_minimal",
        short_description="Городское семейное заведение для обедов и вечерних встреч.",
        description="Заведение добавлено в расширенный каталог WebTavern. План на странице — демонстрационная схема размещения столов.",
        rating="4.42",
        deposit_amount="350.00",
        layout_variant="compact",
        requires_manager_confirmation=False,
    ),
])
