# Generated by Django 6.0.4 on 2026-04-22 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_moderation', 'На модерации'), ('active', 'Активно'), ('blocked', 'Заблокировано')], default='draft', max_length=32, verbose_name='Статус')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='organizations.legalentity', verbose_name='Юридическое лицо')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VenueBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('theme_mode', models.CharField(default='light', max_length=32, verbose_name='Тема')),
                ('accent_color', models.CharField(default='#111827', max_length=32, verbose_name='Акцентный цвет')),
                ('background_variant', models.CharField(default='neutral-surface', max_length=64, verbose_name='Фон')),
                ('text_color', models.CharField(default='#111827', max_length=32, verbose_name='Цвет текста')),
                ('contrast_warning', models.BooleanField(default=False, verbose_name='Есть предупреждение по контрастности')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Брендирование заведения',
                'verbose_name_plural': 'Брендирование заведений',
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='venues/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Изображение заведения',
                'verbose_name_plural': 'Изображения заведений',
            },
        ),
        migrations.CreateModel(
            name='VenueManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Назначение менеджера',
                'verbose_name_plural': 'Назначения менеджеров',
                'unique_together': {('venue', 'manager')},
            },
        ),
    ]
