# Generated by Django 6.0.4 on 2026-04-22 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('desired_date', models.DateField(verbose_name='Желаемая дата')),
                ('desired_time', models.TimeField(verbose_name='Желаемое время')),
                ('guests_count', models.PositiveIntegerField(default=1, verbose_name='Количество гостей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Запись листа ожидания',
                'verbose_name_plural': 'Лист ожидания',
            },
        ),
    ]
