version: "3.9"

services:
  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/frontend/Dockerfile
    env_file:
      - ../../.env
    restart: unless-stopped

  backend:
    build:
      context: ../..
      dockerfile: infra/docker/backend/Dockerfile
    working_dir: /app/backend
    env_file:
      - ../../.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.staging
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  celery:
    build:
      context: ../..
      dockerfile: infra/docker/backend/Dockerfile
    working_dir: /app/backend
    env_file:
      - ../../.env
    command: celery -A config worker -l info
    restart: unless-stopped
    depends_on:
      - backend
      - redis

  celery-beat:
    build:
      context: ../..
      dockerfile: infra/docker/backend/Dockerfile
    working_dir: /app/backend
    env_file:
      - ../../.env
    command: celery -A config beat -l info
    restart: unless-stopped
    depends_on:
      - backend
      - redis

  postgres:
    image: postgres:16-alpine
    env_file:
      - ../../.env
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - frontend
      - backend
    volumes:
      - ../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres_data_staging:
