# Generated by Django 6.0.4 on 2026-04-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('yookassa', 'ЮKassa')], default='yookassa', max_length=32, verbose_name='Провайдер')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='created', max_length=32, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('provider_payment_id', models.CharField(blank=True, max_length=128, verbose_name='ID платежа провайдера')),
                ('idempotence_key', models.CharField(blank=True, max_length=128, verbose_name='Idempotence key')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
