# Generated by Django 6.0.4 on 2026-04-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('requested', 'Запрошен'), ('succeeded', 'Выполнен'), ('failed', 'Ошибка')], default='requested', max_length=32, verbose_name='Статус')),
                ('provider_refund_id', models.CharField(blank=True, max_length=128, verbose_name='ID возврата провайдера')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
            },
        ),
    ]
