# Generated by Django 6.0.4 on 2026-04-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('canvas_width', models.PositiveIntegerField(default=1200, verbose_name='Ширина canvas')),
                ('canvas_height', models.PositiveIntegerField(default=800, verbose_name='Высота canvas')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='layouts/', verbose_name='Фон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='halls.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Схема зала',
                'verbose_name_plural': 'Схемы залов',
            },
        ),
        migrations.CreateModel(
            name='LayoutDecorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('item_type', models.CharField(choices=[('wall', 'Стена'), ('window', 'Окно'), ('bar', 'Барная стойка'), ('entrance', 'Вход'), ('cashier', 'Касса'), ('wc', 'Санузел'), ('column', 'Колонна'), ('plant', 'Растение'), ('sofa', 'Диван'), ('label', 'Подпись')], max_length=32, verbose_name='Тип элемента')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Подпись')),
                ('x', models.IntegerField(default=0, verbose_name='X')),
                ('y', models.IntegerField(default=0, verbose_name='Y')),
                ('width', models.PositiveIntegerField(default=120, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=40, verbose_name='Высота')),
                ('rotation', models.IntegerField(default=0, verbose_name='Поворот')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor_items', to='layouts.tablelayout', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Декоративный элемент схемы',
                'verbose_name_plural': 'Декоративные элементы схемы',
            },
        ),
        migrations.CreateModel(
            name='TableLayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('x', models.IntegerField(default=0, verbose_name='X')),
                ('y', models.IntegerField(default=0, verbose_name='Y')),
                ('width', models.PositiveIntegerField(default=120, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=120, verbose_name='Высота')),
                ('rotation', models.IntegerField(default=0, verbose_name='Поворот')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='layouts.tablelayout', verbose_name='Схема')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout_item', to='tables.table', verbose_name='Стол')),
            ],
            options={
                'verbose_name': 'Элемент схемы',
                'verbose_name_plural': 'Элементы схемы',
            },
        ),
    ]
